### ISSUE TITLE
Receive Exception calling "Parse" with "2" argument(s): "Input string was not in a correct format."

### ISSUE THREAD

**Issue by larrysteele** [ThatBlokeCalledJay/set-json-property#5]
This seems to be very consistent behavior. Here is an example of my appsettings.json file:

{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Error",
      "System": "Error",
      "Microsoft": "Error"
    }
  },
  "CorpGroup": {
    "Web": {
      "Clients": [
        {
          "Interface": "A",
          "Implementation": "A1",
          "OAuthClientId": "A123",
          "OAuthClientSecret": "secret value",
          "OAuthEndpoint": "endpointA",
          "OAuthResource": "resourceguidA",
          "Url": "someapiendpoint"
        }
      ]
    }
  }
}

I'm trying to update the OAuthClientSecret and using property path CorpGroup.Web.Clients[0].OAuthClientSecret. I'm setting the value to a simple string test and receive the error. I've even tried setting a non-array. Here is the full dump of that log:

2019-10-22T02:58:36.1913844Z ##[debug]Evaluating condition for step: 'Set Json Property'
2019-10-22T02:58:36.1914921Z ##[debug]Evaluating: succeeded()
2019-10-22T02:58:36.1915052Z ##[debug]Evaluating succeeded:
2019-10-22T02:58:36.1915375Z ##[debug]=> True
2019-10-22T02:58:36.1915592Z ##[debug]Result: True
2019-10-22T02:58:36.1915810Z ##[section]Starting: Set Json Property
2019-10-22T02:58:36.2069979Z ==============================================================================
2019-10-22T02:58:36.2070038Z Task         : Set Json Property
2019-10-22T02:58:36.2070247Z Description  : A build and release task for updating a json object's property with a specified value.
2019-10-22T02:58:36.2070298Z Version      : 1.0.4
2019-10-22T02:58:36.2070330Z Author       : ThatBlokeCalledJay
2019-10-22T02:58:36.2070362Z Help         : [More Information](https://github.com/ThatBlokeCalledJay/set-json-property/wiki)
2019-10-22T02:58:36.2070409Z ==============================================================================
2019-10-22T02:58:36.9455242Z ##[debug]VstsTaskSdk 0.1 commit _COMMIT_HASH_
2019-10-22T02:58:37.0348678Z ##[debug]Entering F:\a1\_work\_tasks\SetJsonProperty_c4d17080-bdb7-4399-953f-26d67cd16593\1.0.4\task.ps1.
2019-10-22T02:58:37.0631565Z ##[debug]INPUT_JSONFILE: 'F:\a1\_work\r1020\a\Afm-Orc-Release\App\appsettings.qa.json'
2019-10-22T02:58:37.0704818Z ##[debug]INPUT_PROPERTYPATH: 'Logging.LogLevel.Default'
2019-10-22T02:58:37.0705395Z ##[debug]INPUT_PROPERTYVALUE: '"test"'
2019-10-22T02:58:37.0705762Z JSONFile             : F:\a1\_work\r1020\a\Afm-Orc-Release\App\appsettings.qa.json
2019-10-22T02:58:37.0706101Z PropertyPath         : Logging.LogLevel.Default
2019-10-22T02:58:37.0706401Z PropertyValue        : "test"
2019-10-22T02:58:37.0728801Z ==============================================================================
2019-10-22T02:58:37.0824583Z Current value at 'Logging.LogLevel.Default': 'Error'
2019-10-22T02:58:37.0830505Z Replacing 'Error' with '"test"' at 'Logging.LogLevel.Default'
2019-10-22T02:58:37.0849138Z Writing updated json back to file: 'F:\a1\_work\r1020\a\Afm-Orc-Release\App\appsettings.qa.json'
2019-10-22T02:58:37.1194876Z ##[debug]Caught exception from task script.
2019-10-22T02:58:37.1224839Z ##[debug]Error record:
2019-10-22T02:58:37.1766176Z ##[debug]ForEach-Object : Exception calling "Parse" with "2" argument(s): "Input string was not in a correct format."
2019-10-22T02:58:37.1775603Z ##[debug]At F:\a1\_work\_tasks\SetJsonProperty_c4d17080-bdb7-4399-953f-26d67cd16593\1.0.4\task.ps1:53 char:67
2019-10-22T02:58:37.1786712Z ##[debug]+ ...  $jsonInput  | ConvertTo-Json -Depth 50 -Compress |  ForEach-Object {
2019-10-22T02:58:37.1798800Z ##[debug]+                                                          ~~~~~~~~~~~~~~~~
2019-10-22T02:58:37.1809648Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [ForEach-Object], MethodInvocationException
2019-10-22T02:58:37.1821830Z ##[debug]    + FullyQualifiedErrorId : FormatException,Microsoft.PowerShell.Commands.ForEachObjectCommand
2019-10-22T02:58:37.1832782Z ##[debug] 
2019-10-22T02:58:37.1850302Z ##[debug]Script stack trace:
2019-10-22T02:58:37.1880758Z ##[debug]at <ScriptBlock>, F:\a1\_work\_tasks\SetJsonProperty_c4d17080-bdb7-4399-953f-26d67cd16593\1.0.4\task.ps1: line 56
2019-10-22T02:58:37.1894255Z ##[debug]at <ScriptBlock>, F:\a1\_work\_tasks\SetJsonProperty_c4d17080-bdb7-4399-953f-26d67cd16593\1.0.4\task.ps1: line 54
2019-10-22T02:58:37.1905210Z ##[debug]at <ScriptBlock>, F:\a1\_work\_tasks\SetJsonProperty_c4d17080-bdb7-4399-953f-26d67cd16593\1.0.4\task.ps1: line 53
2019-10-22T02:58:37.1915864Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-10-22T02:58:37.1926527Z ##[debug]at <ScriptBlock>, <No file>: line 22
2019-10-22T02:58:37.1937897Z ##[debug]at <ScriptBlock>, <No file>: line 18
2019-10-22T02:58:37.1948173Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-10-22T02:58:37.1969036Z ##[debug]Exception:
2019-10-22T02:58:37.2006677Z ##[debug]System.Management.Automation.MethodInvocationException: Exception calling "Parse" with "2" argument(s): "Input string was not in a correct format." ---> System.FormatException: Input string was not in a correct format.
2019-10-22T02:58:37.2018426Z ##[debug]   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
2019-10-22T02:58:37.2029357Z ##[debug]   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
2019-10-22T02:58:37.2040138Z ##[debug]   at CallSite.Target(Closure , CallSite , Type , Object , NumberStyles )
2019-10-22T02:58:37.2051014Z ##[debug]   --- End of inner exception stack trace ---
2019-10-22T02:58:37.2062857Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-10-22T02:58:37.2073907Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-10-22T02:58:37.2084944Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-10-22T02:58:37.2095240Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-10-22T02:58:37.2564892Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2019-10-22T02:58:37.2565290Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2019-10-22T02:58:37.2566186Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
2019-10-22T02:58:37.2566522Z ##[debug]   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
2019-10-22T02:58:37.2566660Z ##[debug]   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
2019-10-22T02:58:37.2566917Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
2019-10-22T02:58:37.2567639Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
2019-10-22T02:58:37.2577240Z ##[debug]   at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
2019-10-22T02:58:37.2592134Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2019-10-22T02:58:37.2840463Z ##[error]Exception calling "Parse" with "2" argument(s): "Input string was not in a correct format."
2019-10-22T02:58:37.2847265Z ##[debug]Processed: ##vso[task.logissue type=error]Exception calling "Parse" with "2" argument(s): "Input string was not in a correct format."
2019-10-22T02:58:37.2847770Z ##[debug]Processed: ##vso[task.complete result=Failed]
2019-10-22T02:58:37.3116845Z ##[section]Finishing: Set Json Property

**Comment by ThatBlokeCalledJay** [comment]
I appreciate you have dumbed down your appsettings file for the purpose of demonstration, but running the script using the values specified in your log against the above json, using property path "Logging.LogLevel.Default" and value "test"  I am able to successfully update the property.

{
    "Logging": {
        "IncludeScopes": false,
        "LogLevel": {
            "Default": "test",
            "System": "Error",
            "Microsoft": "Error"
        }
    },
    "CorpGroup": {
        "Web": {
            "Clients": [
                {
                    "Interface": "A",
                    "Implementation": "A1",
                    "OAuthClientId": "A123",
                    "OAuthClientSecret": "secret value",
                    "OAuthEndpoint": "endpointA",
                    "OAuthResource": "resourceguidA",
                    "Url": "someapiendpoint"
                }
            ]
        }
    }
}

I then updated the file again, this time using the path mentioned in your description "CorpGroup.Web.Clients[0].OAuthClientSecret" which also yielded expected results.

{
    "Logging": {
        "IncludeScopes": false,
        "LogLevel": {
            "Default": "test",
            "System": "Error",
            "Microsoft": "Error"
        }
    },
    "CorpGroup": {
        "Web": {
            "Clients": [
                {
                    "Interface": "A",
                    "Implementation": "A1",
                    "OAuthClientId": "A123",
                    "OAuthClientSecret": "test",
                    "OAuthEndpoint": "endpointA",
                    "OAuthResource": "resourceguidA",
                    "Url": "someapiendpoint"
                }
            ]
        }
    }
}

There is definitely a problem in your case, and would love to help solve it with you. So, can I ask you to provide your appsettings file, of course obfuscate any sensitive data. In the mean time, I will try a few random variants myself to see if I can stumble across the issue. 

The stack trace indicate an issue parsing a string to a number, which in this case, is a part of a work around to allow for character escaping and unicode character handling during serialisation for example ' \u0027

**Comment by larrysteele** [comment]
Jay, thanks for your prompt response. I’ve attached the appsettings file.

**Comment by ThatBlokeCalledJay** [comment]
@larrysteele hm, I never seem to get notifications from Github, must be an issue with my settings. I've just made my email address public, could you try sending your file again please, to my email address. jay.clark.mail@gmail.com

**Comment by ThatBlokeCalledJay** [comment]
Thanks @larrysteele for providing your settings file. Unfortunately I'm unable to replicate this error locally or running through a live pipe in Azure. I even tried to trick it by providing dodgy characters for the new value.

"1!`¬3£4$55^&*()_+-=[]{};'#@:~,.<>/?/ \ |"

resulted in

 "1!`¬3£4$55^&*()_+-=[]{};'#@:~,.<>/?/ \\ |"

the bloody thing even ended up nicely escaping that back slash for me?

Out of interest, is your build pipe in Azure, or on-prem?

**Comment by larrysteele** [comment]
I’m using an OnPrem Agent in the Release Pipeline.

**Comment by ThatBlokeCalledJay** [comment]
I think you know whats coming next 😊. 

All I have left in my bag of tricks is to ask, are your agents up to date, are you using the latest images etc, are they referencing the latest packages, specifically powershell + Cmdlets etc.

I assume you will be up to date, of course, I'm only suggesting this due to the lack of any other ideas. I'm going to leave this issue open for now  in the hope someone else also comes across this issue and has a slightly varying picture to paint.

In the mean time, I am sorry I wasn't able to resolve this issue for you, but will keep my ear to the ground.

**Comment by ThatBlokeCalledJay** [comment]
Also, just to confirm, your agent version is 2.123.0 or above?

**Comment by larrysteele** [comment]
I have 2.150.3

**Comment by larrysteele** [comment]
I pulled out your task.ps1 file and ran it through PowerShell and get this error:

Exception calling "Parse" with "2" argument(s): "Input string was not in a correct format."
At D:\temp\jsontest.ps1:34 char:23
+             param($m) ([char]([int]::Parse($m.Groups['Value'].Value,
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException

$jsonOutput = $jsonInput  | ConvertTo-Json -Depth 50 -Compress |  ForEach-Object {
    [Regex]::Replace($_,
        "\\u(?<Value>[a-zA-Z0-9]{4})", {
            param($m) ([char]([int]::Parse($m.Groups['Value'].Value,
                [System.Globalization.NumberStyles]::HexNumber))).ToString() } )}


I still can’t figure out why it would be bombing. If I move past this exception in ISE, it does properly commit the change. Obviously the task itself in Azure DevOps won’t allow the commit.

Still puzzled, any thoughts?

Thanks,

Larry

**Comment by larrysteele** [comment]
Jay, I found the problem. It wasn't that value at all. I also have a UNC path in one of the elements, not shown in original file. 

Here is an example in the json:
"PulteGroup": {
    "Orc": {
      "TargetPath": "\\\\servername\\folder1\\folder2\\folder3"
    },

Can you test this again?

Regards,

Larry

**Comment by larrysteele** [comment]
It looks like it dropped all the slashes when I posted this: there are 4 slashes on the begin and then 2 slashes between folders.

**Comment by ThatBlokeCalledJay** [comment]
Hey @larrysteele sorry for the delayed response. I'll certainly get that checked out. I'm wondering if your server name starts with the letter u, this would match the regex pattern, but your server name wouldn't be a valid hex value you see. I'll tweak the regex and see if I can this resolved. e.g. \\u(?<Value>[a-fA-F0-9]{4})

That would fix your problem, but not anybody who has a UNC path like \\\\\\\\ucafe or \\\\\\\\uface etc

**Comment by ThatBlokeCalledJay** [comment]
Good news, I have replicated, and managed to fix the error by tweaking the regex as detailed above. This should resolve your issue @larrysteele, but still poses a problem should a UNC path like \\\\ucafe or \\\\uface. I'll cross that bridge when I come to it.

**Comment by ThatBlokeCalledJay** [comment]
@larrysteele 1.0.5 has been released with the fix. I'll leave this issue open for a little while until you can confirm the problem has been resolved for you.

**Comment by ThatBlokeCalledJay** [comment]
Released regex validation fix with 1.0.5

**Comment by larrysteele** [comment]
Thanks Jay. I'm at Ignite this week and will give it another try next week. Thanks

Larry



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by ThatBlokeCalledJay** [comment]
Very jealous. Should hopefully be pooping along myself too soon in the next year or so. Have a wicked time.

**Comment by larrysteele** [comment]
Jay,

I was able to grab your latest version. It is now working as desired. Thanks so much for your support. I will continue using it as it’s very useful.

Thanks again and best regards,

Larry
